baseURL = "https://james-d-mitchell.github.io/"
languageCode = "en-us"
title = "J. D. Mitchell"
theme="archie"
copyright = "© J. D. Mitchell"
pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableGitInfo = true

[params]
	featherIconsCDN=true

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
lastmod = [":fileModTime", ":git", ":default"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/james-d-mitchell"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publ"
weight = 2

[[menu.main]]
name = "Software"
url = "/soft"
weight = 3
